version: '3.7'

services:

  db:
    image: postgres:latest
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=yourdbname
      - POSTGRES_USER=yourusername
      - POSTGRES_PASSWORD=yourpassword