FROM python:3.8-slim-buster

RUN apt-get update && apt-get install -y libpq-dev gcc
RUN apt-get update && apt-get install -y postgresql-client

COPY requirements.txt requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

WORKDIR /

COPY . .

EXPOSE 8000

RUN chmod +x ./wait-for-postgres.sh

CMD ["./wait-for-postgres.sh", "db", "uvicorn", "main_app:app", "--host", "0.0.0.0", "--port", "8000"]

#CMD ["uvicorn", "main_app:app", "--host", "0.0.0.0", "--port", "8000"]