version: '3.7'

services:

  db:
    build:
      context: .
      dockerfile: Dockerfile_postgres
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwertypoikjh1
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3

  web-backend:
    build:
      context: .
      dockerfile: Dockerfile_fastapi
    ports:
      - 8000:8000
    depends_on:
      - db

  web-frontend:
    build:
      context: ./client
      dockerfile: Dockerfile_react
    ports:
      - 3000:3000
    depends_on:
      - web-backend

volumes:
  db_data: 